blank_issues_enabled: false
contact_links:
  - name: Soporte de la comunidad
    url: https://github.com/36095/la-voz-del-aire-app/discussions
    about: Haz y responde preguntas aquí.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Informa sobre las vulnerabilidades de seguridad aquí.
